
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"

// export const GET_CART_LOADING = "GET_CART_LOADING"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"

export const Single_PRODUCT_REQUEST = "Single_PRODUCT_REQUEST";
export const Single_PRODUCT_SUCCESS = "Single_PRODUCT_SUCCESS";
export const Single_PRODUCT_FAILURE = "Single_PRODUCT_FAILURE";

export const ORDER_PRODUCT_REQUEST = "ORDER_PRODUCT_REQUEST";
export const ORDER_PRODUCT_SUCCESS = "ORDER_PRODUCT_SUCCESS";
export const ORDER_PRODUCT_FAILURE = "ORDER_PRODUCT_FAILURE";